
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},e),ba=(a,b)=>{throw b;},ca="object"===typeof window,k="function"===typeof importScripts,da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,l="",ea,fa,ha,fs,ia,ja;
if(da)l=k?require("path").dirname(l)+"/":__dirname+"/",ja=()=>{ia||(fs=require("fs"),ia=require("path"))},ea=function(a,b){ja();a=ia.normalize(a);return fs.readFileSync(a,b?null:"utf8")},ha=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a},fa=(a,b,c)=>{ja();a=ia.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof
ka))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ba=(a,b)=>{if(noExitRuntime||0<la)throw process.exitCode=a,b;b instanceof ka||m("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ca||k)k?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},k&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var t=e.print||console.log.bind(console),m=e.printErr||console.warn.bind(console);Object.assign(e,aa);aa=null;e.quit&&(ba=e.quit);
function ma(a){na||(na={});na[a]||(na[a]=1,m(a))}var na,v;e.wasmBinary&&(v=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");
function oa(a,b,c="i8"){"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":pa[a>>0]=b;break;case "i8":pa[a>>0]=b;break;case "i16":qa[a>>1]=b;break;case "i32":z[a>>2]=b;break;case "i64":ra=[b>>>0,(A=b,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];z[a>>2]=ra[0];z[a+4>>2]=ra[1];break;case "float":sa[a>>2]=b;break;case "double":ta[a>>3]=b;break;default:y("invalid type for setValue: "+c)}}var ua,B=!1,va;
function wa(a){var b=xa(a.length);a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function D(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function za(a,b,c){var d=0;if(!(0<c))return 0;var f=d;c=d+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(d>=c)break;b[d++]=h}else{if(2047>=h){if(d+1>=c)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=c)break;b[d++]=224|h>>12}else{if(d+3>=c)break;b[d++]=240|h>>18;b[d++]=128|h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0;return d-f}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Ba,pa,C,qa,z,Ca,sa,ta,Da=[],Ea=[],Fa=[],Ga=[],Ha=!1,la=0;function Ia(){var a=e.preRun.shift();Da.unshift(a)}var E=0,Ja=null,Ka=null;e.preloadedImages={};e.preloadedAudios={};
function y(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";m(a);B=!0;va=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function La(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="triangle_c.wasm";if(!La()){var Ma=F;F=e.locateFile?e.locateFile(Ma,l):l+Ma}function Na(){var a=F;try{if(a==F&&v)return new Uint8Array(v);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function Oa(){if(!v&&(ca||k)){if("function"===typeof fetch&&!F.startsWith("file://"))return fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return Na()});if(fa)return new Promise(function(a,b){fa(F,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Na()})}var A,ra;
function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Pa;"number"===typeof c?void 0===b.Y?dynCall_v.call(null,c):dynCall_vi.apply(null,[c,b.Y]):c(void 0===b.Y?null:b.Y)}}}function Qa(a){a instanceof ka||"unwind"==a||ba(1,a)}function Ra(a){if(!Ha&&!B)try{a()}catch(b){Qa(b)}}function Sa(a,b){return setTimeout(function(){Ra(a)},b)}
function Ta(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function Ua(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Va(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Wa=1,Xa=[],G=[],Ya=[],Za=[],$a=[1,1,2,2,4,4,4,2,3,4,8];
function ab(a){for(var b=Wa++,c=a.length;c<b;c++)a[c]=null;return b}function bb(a){return 32-Math.clz32(0===a?0:a-1)}function cb(a,b){a.va||(a.va=a.getContext,a.getContext=function(d,f){f=a.va(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.ya?a.getContext("webgl2",b):a.getContext("webgl",b);return c?db(c,b):0}
function db(a,b){var c=ab(Za),d={ib:c,attributes:b,version:b.ya,X:a};a.canvas&&(a.canvas.Za=d);Za[c]=d;("undefined"===typeof b.Oa||b.Oa)&&eb(d);d.za=d.X.getParameter(34921);d.S=[];for(a=0;a<d.za;a++)d.S[a]={enabled:!1,T:!1,size:0,type:0,ha:0,ba:0,V:0,ka:null};a=bb(2097152);d.N=[];d.da=[];d.N.length=d.da.length=a+1;d.R=[];d.W=[];d.R.length=d.W.length=a+1;d.Ka=[];d.Ka.length=a+1;for(b=0;b<=a;++b){d.Ka[b]=null;d.N[b]=d.da[b]=0;d.R[b]=[];d.W[b]=[];var f=d.R[b],g=d.W[b];f.length=g.length=64;for(var h=
0;64>h;++h)f[h]=g[h]=null}return c}
function eb(a){a||(a=H);if(!a.Sa){a.Sa=!0;var b=a.X;Ta(b);Ua(b);Va(b);b.fb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.mb=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.qa=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.qa)b.qa=b.getExtension("EXT_disjoint_timer_query");b.pb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var fb={},H,gb,hb;hb=da?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function ib(a,b){jb=a;kb=b;if(I)if(mb||(mb=!0),0==a)J=function(){var d=Math.max(0,nb+b-hb())|0;setTimeout(ob,d)};else if(1==a)J=function(){pb(ob)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);k?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}J=function(){setImmediate(ob)}}}
function qb(a){function b(){if(c<rb){if(!(noExitRuntime||0<la))try{sb(va)}catch(d){Qa(d)}return!1}return!0}!I||y("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");I=a;var c=rb;mb=!1;ob=function(){if(!B)if(0<tb.length){var d=Date.now(),f=tb.shift();f.Pa(f.Y);if(ub){var g=ub,h=0==g%1?g-1:Math.floor(g);ub=f.cb?h:(8*g+(h+.5))/9}t('main loop blocker "'+f.name+'" took '+
(Date.now()-d)+" ms");e.setStatus&&(d=e.statusMessage||"Please wait...",f=ub,g=vb.gb,f?f<g?e.setStatus(d+" ("+(g-f)+"/"+g+")"):e.setStatus(d):e.setStatus(""));b()&&setTimeout(ob,0)}else if(b())if(K=K+1|0,1==jb&&1<kb&&0!=K%kb)J();else{0==jb&&(nb=hb());if(H)for(d=H.R,H.R=H.W,H.W=d,d=H.N,H.N=H.da,H.da=d,d=bb(2097152),f=0;f<=d;++f)H.N[f]=0;B||e.preMainLoop&&!1===e.preMainLoop()||(Ra(a),e.postMainLoop&&e.postMainLoop());b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Va&&SDL.audio.Va(),J())}}}
var mb=!1,J=null,rb=0,I=null,jb=0,kb=0,K=0,tb=[];function wb(){rb++;var a=jb,b=kb,c=I;I=null;qb(c);ib(a,b);J()}var vb={},nb,ob,ub,xb=!1,yb=!1,zb=[];
function Ab(){function a(){yb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Bb){Bb=!0;try{Cb=!0}catch(c){Cb=!1,t("warning: no blob constructor, cannot create blobs with mimetypes")}Db="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Cb?null:t("warning: no BlobBuilder");Eb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;e.Ea||"undefined"!==typeof Eb||(t("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.Ea=!0);e.preloadPlugins.push({canHandle:function(c){return!e.Ea&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(Cb)try{h=new Blob([c],{type:Fb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Fb(d)}))}catch(p){ma("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Db,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var n=Eb.createObjectURL(h),q=new Image;q.onload=()=>{q.complete||y("Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=q.width;p.height=q.height;p.getContext("2d").drawImage(q,0,0);e.preloadedImages[d]=p;Eb.revokeObjectURL(n);f&&f(c)};q.onerror=()=>{t("Image "+n+" could not be decoded");g&&g()};q.src=n}});e.preloadPlugins.push({canHandle:function(c){return!e.qb&&c.substr(-4)in
{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(r){q||(q=!0,e.preloadedAudios[d]=r,f&&f(c))}function n(){q||(q=!0,e.preloadedAudios[d]=new Audio,g&&g())}var q=!1;if(Cb){try{var p=new Blob([c],{type:Fb(d)})}catch(r){return n()}p=Eb.createObjectURL(p);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!q){t("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",w=0,x=0,O=0;O<c.length;O++)for(w=
w<<8|c[O],x+=8;6<=x;){var lb=w>>x-6&63;x-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[lb]}2==x?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],r+="=="):4==x&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],r+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+r;h(u)}};u.src=p;Sa(function(){h(u)},1E4)}else return n()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!yb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Gb(a,b,c,d){if(b&&e.U&&a==e.canvas)return e.U;var f;if(b){var g={antialias:!1,alpha:!1,ya:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof fb&&(f=cb(a,g)))var n=Za[f].X}else n=a.getContext("2d");if(!n)return null;c&&(b||"undefined"===typeof L||y("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.U=n,b&&(H=Za[f],e.U=L=H&&H.X),e.wb=b,zb.forEach(function(q){q()}),Ab());return n}
var Hb=!1,Ib=void 0,M=void 0;
function Jb(a,b){function c(){xb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Kb,Ib&&d.requestPointerLock(),xb=!0,M?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=Ca[SDL.screen>>2]|8388608),Lb(e.canvas),Mb()):Lb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),M?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=Ca[SDL.screen>>2]&
-8388609),Lb(e.canvas),Mb()):Lb(d));if(e.onFullScreen)e.onFullScreen(xb);if(e.onFullscreen)e.onFullscreen(xb)}Ib=a;M=b;"undefined"===typeof Ib&&(Ib=!0);"undefined"===typeof M&&(M=!1);var d=e.canvas;Hb||(Hb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Kb(){if(!xb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Nb=0;function pb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Nb)Nb=b+1E3/60;else for(;b+2>=Nb;)Nb+=1E3/60;setTimeout(a,Math.max(Nb-b,0))}}
function Fb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ob=0,Pb=0,Qb=0,Rb=0;
function Sb(a){if(yb)"mousemove"!=a.type&&"mozMovementX"in a?Qb=Rb=0:(Qb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Rb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Ob=SDL.nb+Qb,Pb=SDL.ob+Rb):(Ob+=Qb,Pb+=Rb);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,Qb=f-Ob,Rb=a-Pb,Ob=f,Pb=a)}}var Tb=[];function Mb(){var a=e.canvas;Tb.forEach(function(b){b(a.width,a.height)})}function Ub(a,b,c){Lb(e.canvas,a,b);c||Mb()}
function Lb(a,b,c){b&&c?(a.Ya=b,a.Ra=c):(b=a.Ya,c=a.Ra);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}M?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Vb={},Bb,Cb,Db,Eb;
function Wb(a,b,c,d,f){this.id=a;this.y=this.x=0;this.ga=!1;this.Ja=this.Ia=0;this.width=b;this.height=c;this.Ha=b;this.Ga=c;this.title=d;this.share=f;this.attributes=N;this.buttons=0;this.keys=[];this.ea=[];this.ma=this.xa=this.fa=this.Fa=this.Z=this.pa=this.Ca=this.ua=this.La=this.title=null}
function Xb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(da)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){y("randomDevice")}}function Yb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Zb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Yb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function $b(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ac(a){if("/"===a)return"/";a=Zb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function bc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Yb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var cc=[];function dc(a,b){cc[a]={input:[],output:[],P:b};ec(a,fc)}
var fc={open:function(a){var b=cc[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.P.flush(a.tty)},flush:function(a){a.tty.P.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.P.wa)throw new P(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.P.wa(a.tty)}catch(n){throw new P(29);}if(void 0===h&&0===f)throw new P(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.P.ia)throw new P(60);try{for(var f=
0;f<d;f++)a.tty.P.ia(a.tty,b[c+f])}catch(g){throw new P(29);}d&&(a.node.timestamp=Date.now());return f}},hc={wa:function(a){if(!a.input.length){var b=null;if(da){b=Buffer.alloc(256);var c=0;try{c=fs.readSync(process.stdin.fd,b,0,256,null)}catch(d){if(d.toString().includes("EOF"))c=0;else throw d;}b=0<c?b.slice(0,c).toString("utf-8"):null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=gc(b,!0)}return a.input.shift()},ia:function(a,b){null===b||10===b?(t(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(D(a.output,0)),a.output=[])}},ic={ia:function(a,b){null===b||10===b?(m(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(m(D(a.output,0)),a.output=[])}},Q={J:null,L:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,b,
c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.J||(Q.J={dir:{node:{M:Q.G.M,K:Q.G.K,lookup:Q.G.lookup,$:Q.G.$,rename:Q.G.rename,unlink:Q.G.unlink,rmdir:Q.G.rmdir,readdir:Q.G.readdir,symlink:Q.G.symlink},stream:{O:Q.H.O}},file:{node:{M:Q.G.M,K:Q.G.K},stream:{O:Q.H.O,read:Q.H.read,write:Q.H.write,la:Q.H.la,Aa:Q.H.Aa,Da:Q.H.Da}},link:{node:{M:Q.G.M,K:Q.G.K,readlink:Q.G.readlink},stream:{}},na:{node:{M:Q.G.M,K:Q.G.K},stream:jc}});c=kc(a,b,c,d);16384===(c.mode&61440)?(c.G=Q.J.dir.node,c.H=
Q.J.dir.stream,c.F={}):32768===(c.mode&61440)?(c.G=Q.J.file.node,c.H=Q.J.file.stream,c.I=0,c.F=null):40960===(c.mode&61440)?(c.G=Q.J.link.node,c.H=Q.J.link.stream):8192===(c.mode&61440)&&(c.G=Q.J.na.node,c.H=Q.J.na.stream);c.timestamp=Date.now();a&&(a.F[b]=c,a.timestamp=c.timestamp);return c},hb:function(a){return a.F?a.F.subarray?a.F.subarray(0,a.I):new Uint8Array(a.F):new Uint8Array(0)},ra:function(a,b){var c=a.F?a.F.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),
c=a.F,a.F=new Uint8Array(b),0<a.I&&a.F.set(c.subarray(0,a.I),0))},Wa:function(a,b){if(a.I!=b)if(0==b)a.F=null,a.I=0;else{var c=a.F;a.F=new Uint8Array(b);c&&a.F.set(c.subarray(0,Math.min(b,a.I)));a.I=b}},G:{M:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.I:40960===(a.mode&61440)?a.link.length:0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);
b.Ma=4096;b.blocks=Math.ceil(b.size/b.Ma);return b},K:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Wa(a,b.size)},lookup:function(){throw lc[44];},$:function(a,b,c,d){return Q.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=mc(b,c)}catch(g){}if(d)for(var f in d.F)throw new P(55);}delete a.parent.F[a.name];a.parent.timestamp=Date.now();a.name=c;b.F[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,
b){delete a.F[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=mc(a,b),d;for(d in c.F)throw new P(55);delete a.F[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.F)a.F.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},H:{read:function(a,b,c,d,f){var g=a.node.F;if(f>=a.node.I)return 0;a=Math.min(a.node.I-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,
f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.F||a.F.subarray)){if(g)return a.F=b.subarray(c,c+d),a.I=d;if(0===a.I&&0===f)return a.F=b.slice(c,c+d),a.I=d;if(f+d<=a.I)return a.F.set(b.subarray(c,c+d),f),d}Q.ra(a,f+d);if(a.F.subarray&&b.subarray)a.F.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.F[f+g]=b[c+g];a.I=Math.max(a.I,f+d);return d},O:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&
61440)&&(b+=a.node.I);if(0>b)throw new P(28);return b},la:function(a,b,c){Q.ra(a.node,b+c);a.node.I=Math.max(a.node.I,b+c)},Aa:function(a,b,c,d,f,g){if(0!==b)throw new P(28);if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.F;if(g&2||a.buffer!==Ba){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;y();c=void 0;if(!c)throw new P(48);pa.set(a,c)}else d=!1,c=a.byteOffset;return{V:c,$a:d}},Da:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new P(43);
if(f&2)return 0;Q.H.write(a,b,0,d,c,!1);return 0}}},nc=null,oc={},pc=[],qc=1,rc=null,sc=!0,P=null,lc={},R=(a,b={})=>{a=bc("/",a);if(!a)return{path:"",node:null};var c={ta:!0,ja:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ja)throw new P(32);a=Yb(a.split("/").filter(h=>!!h),!1);var f=nc;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=mc(f,a[d]);c=Zb(c+"/"+a[d]);f.aa&&(!g||g&&b.ta)&&(f=f.aa.root);if(!g||b.sa)for(g=0;40960===(f.mode&61440);)if(f=tc(c),c=bc($b(c),f),f=R(c,
{ja:b.ja}).node,40<g++)throw new P(32);}return{path:c,node:f}},uc=a=>{for(var b;;){if(a===a.parent)return a=a.L.Ba,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},vc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%rc.length},mc=(a,b)=>{var c;if(c=(c=wc(a,"x"))?c:a.G.lookup?0:2)throw new P(c,a);for(c=rc[vc(a.id,b)];c;c=c.Ua){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.G.lookup(a,b)},kc=(a,b,c,d)=>{a=new xc(a,b,c,d);b=vc(a.parent.id,
a.name);a.Ua=rc[b];return rc[b]=a},yc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},zc=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},wc=(a,b)=>{if(sc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ac=(a,b)=>{try{return mc(a,b),20}catch(c){}return wc(a,"wx")},Bc=(a=0,b=4096)=>{for(;a<=b;a++)if(!pc[a])return a;throw new P(33);},Dc=a=>{Cc||(Cc=function(){},Cc.prototype={object:{get:function(){return this.node},
set:function(c){this.node=c}}});a=Object.assign(new Cc,a);var b=Bc(void 0,void 0);a.fd=b;return pc[b]=a},jc={open:a=>{a.H=oc[a.node.rdev].H;a.H.open&&a.H.open(a)},O:()=>{throw new P(70);}},ec=(a,b)=>{oc[a]={H:b}},Ec=(a,b)=>{var c="/"===b,d=!b;if(c&&nc)throw new P(10);if(!c&&!d){var f=R(b,{ta:!1});b=f.path;f=f.node;if(f.aa)throw new P(10);if(16384!==(f.mode&61440))throw new P(54);}b={type:a,rb:{},Ba:b,Ta:[]};a=a.L(b);a.L=b;b.root=a;c?nc=a:f&&(f.aa=b,f.L&&f.L.Ta.push(b))},S=(a,b,c)=>{var d=R(a,{parent:!0}).node;
a=ac(a);if(!a||"."===a||".."===a)throw new P(28);var f=Ac(d,a);if(f)throw new P(f);if(!d.G.$)throw new P(63);return d.G.$(d,a,b,c)},Fc=(a,b,c)=>{"undefined"===typeof c&&(c=b,b=438);S(a,b|8192,c)},Gc=(a,b)=>{if(!bc(a))throw new P(44);var c=R(b,{parent:!0}).node;if(!c)throw new P(44);b=ac(b);var d=Ac(c,b);if(d)throw new P(d);if(!c.G.symlink)throw new P(63);c.G.symlink(c,b,a)},tc=a=>{a=R(a).node;if(!a)throw new P(44);if(!a.G.readlink)throw new P(28);return bc(uc(a.parent),a.G.readlink(a))},Ic=(a,b,c)=>
{if(""===a)throw new P(44);if("string"===typeof b){var d=yc[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Zb(a);try{f=R(a,{sa:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new P(20);}else f=S(a,c,0),d=!0;if(!f)throw new P(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new P(54);if(!d&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&
("r"!==zc(b)||b&512)?31:wc(f,zc(b)):44))throw new P(c);if(b&512){c=f;c="string"===typeof c?R(c,{sa:!0}).node:c;if(!c.G.K)throw new P(63);if(16384===(c.mode&61440))throw new P(31);if(32768!==(c.mode&61440))throw new P(28);if(d=wc(c,"w"))throw new P(d);c.G.K(c,{size:0,timestamp:Date.now()})}b&=-131713;f=Dc({node:f,path:uc(f),flags:b,seekable:!0,position:0,H:f.H,Xa:[],error:!1});f.H.open&&f.H.open(f);!e.logReadFiles||b&1||(Hc||(Hc={}),a in Hc||(Hc[a]=1));return f},Jc=(a,b,c,d)=>{var f=void 0;if(0>c||
0>f)throw new P(28);if(null===a.fd)throw new P(8);if(0===(a.flags&2097155))throw new P(8);if(16384===(a.node.mode&61440))throw new P(31);if(!a.H.write)throw new P(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new P(8);if(!a.seekable||!a.H.O)throw new P(70);a.position=a.H.O(a,0,2);a.Xa=[]}var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new P(70);b=a.H.write(a,b,0,c,f,d);g||(a.position+=b)},Kc=()=>{P||(P=function(a,b){this.node=b;this.message="FS error"},P.prototype=
Error(),P.prototype.constructor=P,[44].forEach(a=>{lc[a]=new P(a);lc[a].stack="<generic error, no stack>"}))},Lc,Mc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Nc=()=>{var a="/";a="string"===typeof a?a:uc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Zb(a+"/"+c);try{S(a,16895,0)}catch(d){}}}},Pc=(a,b,c)=>{a=Zb("/dev/"+a);var d=Mc(!!b,!!c);Oc||(Oc=64);var f=Oc++<<8|0;ec(f,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,n,q)=>
{for(var p=0,u=0;u<q;u++){try{var r=b()}catch(w){throw new P(29);}if(void 0===r&&0===p)throw new P(6);if(null===r||void 0===r)break;p++;h[n+u]=r}p&&(g.node.timestamp=Date.now());return p},write:(g,h,n,q)=>{for(var p=0;p<q;p++)try{c(h[n+p])}catch(u){throw new P(29);}q&&(g.node.timestamp=Date.now());return p}});Fc(a,d,f)},Oc,Cc,Hc,T=null,U=null,N=null,Qc={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,
135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Rc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Sc(){var a=T,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Tc(a){T&&T.ma&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii.apply(null,[T.ma,T.id,a]))}
function Uc(a,b){if(T){var c=Rc(a);if(-1!=c){var d=b&&T.keys[c];T.keys[c]=b;T.ea[a]=b;T.xa&&(d&&(b=2),dynCall_viiiii.apply(null,[T.xa,T.id,c,a,b,Sc()]))}}}function Vc(){Wc()}function Xc(){Wc()}function Yc(a){Uc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Zc(a){Uc(a.keyCode,0)}function $c(){if(T)for(var a=0;a<T.ea.length;++a)T.ea[a]&&Uc(a,0)}function ad(a){T&&(Sb(a),a.target==e.canvas&&T.pa&&dynCall_vidd.apply(null,[T.pa,T.id,Ob,Pb]))}
function bd(a){T&&a.target==e.canvas&&T.Z&&dynCall_vii.apply(null,[T.Z,T.id,1])}function cd(a){T&&a.target==e.canvas&&T.Z&&dynCall_vii.apply(null,[T.Z,T.id,0])}function dd(a,b){if(T&&(Sb(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){T.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else T.buttons&=~(1<<c);T.Ca&&dynCall_viiii.apply(null,[T.Ca,T.id,c,b,Sc()])}}function ed(a){T&&dd(a,1)}function V(a){T&&dd(a,0)}
function fd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(T&&T.Fa&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;dynCall_vidd.apply(null,[T.Fa,T.id,b,c]);a.preventDefault()}}
function gd(){T&&T.La&&Ra(function(){dynCall_viii.apply(null,[T.La,T.id,T.width,T.height])})}function hd(){T&&T.ua&&Ra(function(){dynCall_viii.apply(null,[T.ua,T.id,T.width,T.height])})}var W={},jd=null,kd=null;
function Wc(){if(K!==kd||!K){jd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;kd=K;for(var a=0;a<jd.length;++a){var b=jd[a];if(b){W[a]||(t("glfw joystick connected:",a),W[a]={id:wa(gc(b.id)),bb:b.buttons.length,ab:b.axes.length,buttons:wa(Array(b.buttons.length)),axes:wa(Array(4*b.axes.length))});for(var c=W[a],d=0;d<b.buttons.length;++d)oa(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)oa(c.axes+4*d,b.axes[d],"float")}else W[a]&&
(t("glfw joystick disconnected",a),X(W[a].id),X(W[a].buttons),X(W[a].axes),delete W[a])}}}
function ld(a){function b(n){var q="/.glfw_dropped_files/"+n.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=r=>{if(2!=p.readyState)++g,t("failed to read dropped file: "+n.name+": "+p.error);else{var w=new Uint8Array(r.target.result);r={};r.flags=r.flags||577;var x=Ic(q,r.flags,r.mode);if("string"===typeof w){var O=new Uint8Array(Aa(w)+1);w=za(w,O,O.length);Jc(x,O,w,r.Na)}else if(ArrayBuffer.isView(w))Jc(x,w,w.byteLength,r.Na);else throw Error("Unsupported data type");if(null===x.fd)throw new P(8);
x.Qa&&(x.Qa=null);try{x.H.close&&x.H.close(x)}catch(lb){throw lb;}finally{pc[x.fd]=null}x.fd=null;if(++g===f){dynCall_viii.apply(null,[T.fa,T.id,f,c]);for(r=0;r<d.length;++r)X(d[r]);X(c)}}};p.readAsArrayBuffer(n);var u=wa(gc(q));d.push(u);oa(c+4*h,u,"i8*")}if(T&&T.fa&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=wa(Array(4*a.dataTransfer.files.length)),d=[],f=a.dataTransfer.files.length,g=0;Nc();for(var h=0;h<f;++h)b(a.dataTransfer.files[h]);return!1}}
function md(a){if(T&&T.fa)return a.preventDefault(),!1}function nd(a){try{a()}catch(b){y(b)}}var Y=0,Z=null,od=[],pd={},qd={},rd=0,sd=null,td=[];function ud(a){var b={},c;for(c in a)(function(d){var f=a[d];b[d]="function"===typeof f?function(){od.push(d);try{return f.apply(null,arguments)}finally{B||(od.pop()===d||y(void 0),Z&&1===Y&&0===od.length&&(Y=0,nd(e._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.sb()))}}:f})(c);return b}
function vd(){var a=xa(4108),b=a+12;z[a>>2]=b;z[a+4>>2]=b+4096;b=od[0];var c=pd[b];void 0===c&&(c=rd++,pd[b]=c,qd[c]=b);z[a+8>>2]=c;return a}
function wd(a){if(!B)if(0===Y){var b=!1,c=!1;a(()=>{if(!B&&(b=!0,c)){Y=2;nd(()=>e._asyncify_start_rewind(Z));"undefined"!==typeof Vb&&I&&wb();var d=!1;try{var f=(0,e.asm[qd[z[Z+8>>2]]])()}catch(n){f=n,d=!0}var g=!1;if(!Z){var h=sd;h&&(sd=null,(d?h.reject:h.resolve)(f),g=!0)}if(d&&!g)throw f;}});c=!0;b||(Y=1,Z=vd(),nd(()=>e._asyncify_start_unwind(Z)),"undefined"!==typeof Vb&&I&&(J=null,rb++))}else 2===Y?(Y=0,nd(e._asyncify_stop_rewind),X(Z),Z=null,td.forEach(d=>Ra(d))):y("invalid state: "+Y)}var L;
e.requestFullscreen=function(a,b){Jb(a,b)};e.requestAnimationFrame=function(a){pb(a)};e.setCanvasSize=function(a,b,c){Ub(a,b,c)};e.pauseMainLoop=function(){J=null;rb++};e.resumeMainLoop=function(){wb()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Gb(a,b,c,d)};
function xc(a,b,c,d){a||(a=this);this.parent=a;this.L=a.L;this.aa=null;this.id=qc++;this.name=b;this.mode=c;this.G={};this.H={};this.rdev=d}Object.defineProperties(xc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Kc();rc=Array(4096);Ec(Q,"/");S("/tmp",16895,0);S("/home",16895,0);S("/home/web_user",16895,0);
(()=>{S("/dev",16895,0);ec(259,{read:()=>0,write:(b,c,d,f)=>f});Fc("/dev/null",259);dc(1280,hc);dc(1536,ic);Fc("/dev/tty",1280);Fc("/dev/tty1",1536);var a=Xb();Pc("random",a);Pc("urandom",a);S("/dev/shm",16895,0);S("/dev/shm/tmp",16895,0)})();
(()=>{S("/proc",16895,0);var a=S("/proc/self",16895,0);S("/proc/self/fd",16895,0);Ec({L:()=>{var b=kc(a,"fd",16895,73);b.G={lookup:(c,d)=>{var f=pc[+d];if(!f)throw new P(8);c={parent:null,L:{Ba:"fake"},G:{readlink:()=>f.path}};return c.parent=c}};return b}},"/proc/self/fd")})();function gc(a,b){var c=Array(Aa(a)+1);a=za(a,c,c.length);b&&(c.length=a);return c}
var xd={n:function(){y("OOM")},o:function(a){wd(b=>Sa(b,a))},c:function(a,b){L.attachShader(G[a],Ya[b])},m:function(a){L.clear(a)},d:function(a){L.compileShader(Ya[a])},s:function(){var a=ab(G),b=L.createProgram();b.name=a;b.lb=b.jb=b.kb=0;b.tb=1;G[a]=b;return a},f:function(a){var b=ab(Ya);Ya[b]=L.createShader(a);return b},l:function(a,b,c){var d=b+c;gb=!1;for(var f=0;f<H.za;++f){var g=H.S[f];if(g.T&&g.enabled){gb=!0;var h=g.ba;h=0<h?d*h:g.size*$a[g.type-5120]*d;var n=bb(h);var q=H.R[n],p=H.N[n];
H.N[n]=H.N[n]+1&63;var u=q[p];u?n=u:(u=L.getParameter(34964),q[p]=L.createBuffer(),L.bindBuffer(34962,q[p]),L.bufferData(34962,1<<n,35048),L.bindBuffer(34962,u),n=q[p]);L.bindBuffer(34962,n);L.bufferSubData(34962,0,C.subarray(g.V,g.V+h));g.ka.call(L,f,g.size,g.type,g.ha,g.ba,0)}}L.drawArrays(a,b,c);gb&&L.bindBuffer(34962,Xa[L.oa])},b:function(a){H.S[a].enabled=!0;L.enableVertexAttribArray(a)},g:function(a,b){return L.getAttribLocation(G[a],b?D(C,b,void 0):"")},r:function(a){a=G[a];L.linkProgram(a);
a.ub=0;a.vb={}},e:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?z[d+4*g>>2]:-1,n=z[c+4*g>>2];h=n?D(C,n,0>h?void 0:h):"";f+=h}L.shaderSource(Ya[a],f)},q:function(a){a=G[a];L.useProgram(a);L.eb=a},p:function(a,b,c,d,f){var g=H.S[a];L.oa?(g.T=!1,L.vertexAttribIPointer(a,b,c,d,f)):(g.size=b,g.type=c,g.ha=!1,g.ba=d,g.V=f,g.T=!0,g.ka=function(h,n,q,p,u,r){this.vertexAttribIPointer(h,n,q,u,r)})},t:function(a,b,c,d,f,g){var h=H.S[a];L.oa?(h.T=!1,L.vertexAttribPointer(a,b,c,!!d,f,g)):(h.size=b,h.type=
c,h.ha=d,h.ba=f,h.V=g,h.T=!0,h.ka=function(n,q,p,u,r,w){this.vertexAttribPointer(n,q,p,u,r,w)})},j:function(a,b,c,d,f){var g;for(g=0;g<U.length&&null!==U[g];g++);if(0<g)throw"glfwCreateWindow only supports one window at time currently";var h=g+1;if(0>=a||0>=b)h=0;else{d?Jb():Ub(a,b);for(g=0;g<U.length&&null==U[g];g++);d=0<N[139265];g==U.length&&(d?e.U=Gb(e.canvas,!0,!0,{antialias:1<N[135181],depth:0<N[135173],stencil:0<N[135174],alpha:0<N[135172]}):Ab());!e.U&&d?h=0:(a=new Wb(h,a,b,c,f),h-1==U.length?
U.push(a):U[h-1]=a,T=a,h=a.id)}return h},k:function(){if(U)return 1;hb();N=Qc;U=[];T=null;window.addEventListener("gamepadconnected",Vc,!0);window.addEventListener("gamepaddisconnected",Xc,!0);window.addEventListener("keydown",Yc,!0);window.addEventListener("keypress",Tc,!0);window.addEventListener("keyup",Zc,!0);window.addEventListener("blur",$c,!0);e.canvas.addEventListener("touchmove",ad,!0);e.canvas.addEventListener("touchstart",ed,!0);e.canvas.addEventListener("touchcancel",V,!0);e.canvas.addEventListener("touchend",
V,!0);e.canvas.addEventListener("mousemove",ad,!0);e.canvas.addEventListener("mousedown",ed,!0);e.canvas.addEventListener("mouseup",V,!0);e.canvas.addEventListener("wheel",fd,!0);e.canvas.addEventListener("mousewheel",fd,!0);e.canvas.addEventListener("mouseenter",bd,!0);e.canvas.addEventListener("mouseleave",cd,!0);e.canvas.addEventListener("drop",ld,!0);e.canvas.addEventListener("dragover",md,!0);Tb.push(function(a,b){if(T){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||
document.webkitIsFullScreen?(T.Ia=T.x,T.Ja=T.y,T.Ha=T.width,T.Ga=T.height,T.x=T.y=0,T.width=screen.width,T.height=screen.height,T.ga=!0):1==T.ga?(T.x=T.Ia,T.y=T.Ja,T.width=T.Ha,T.height=T.Ga,T.ga=!1):T.width!=a||T.height!=b?(T.width=a,T.height=b):c=!1;c&&(Ub(T.width,T.height,!0),gd(),hd())}});return 1},h:function(){},i:function(){window.removeEventListener("gamepadconnected",Vc,!0);window.removeEventListener("gamepaddisconnected",Xc,!0);window.removeEventListener("keydown",Yc,!0);window.removeEventListener("keypress",
Tc,!0);window.removeEventListener("keyup",Zc,!0);window.removeEventListener("blur",$c,!0);e.canvas.removeEventListener("touchmove",ad,!0);e.canvas.removeEventListener("touchstart",ed,!0);e.canvas.removeEventListener("touchcancel",V,!0);e.canvas.removeEventListener("touchend",V,!0);e.canvas.removeEventListener("mousemove",ad,!0);e.canvas.removeEventListener("mousedown",ed,!0);e.canvas.removeEventListener("mouseup",V,!0);e.canvas.removeEventListener("wheel",fd,!0);e.canvas.removeEventListener("mousewheel",
fd,!0);e.canvas.removeEventListener("mouseenter",bd,!0);e.canvas.removeEventListener("mouseleave",cd,!0);e.canvas.removeEventListener("drop",ld,!0);e.canvas.removeEventListener("dragover",md,!0);e.canvas.width=e.canvas.height=1;T=U=null},a:function(a,b){N[a]=b}};
(function(){function a(g){g=g.exports;g=ud(g);e.asm=g;ua=e.asm.u;Ba=g=ua.buffer;e.HEAP8=pa=new Int8Array(g);e.HEAP16=qa=new Int16Array(g);e.HEAP32=z=new Int32Array(g);e.HEAPU8=C=new Uint8Array(g);e.HEAPU16=new Uint16Array(g);e.HEAPU32=Ca=new Uint32Array(g);e.HEAPF32=sa=new Float32Array(g);e.HEAPF64=ta=new Float64Array(g);Ea.unshift(e.asm.v);E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);0==E&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka&&(g=Ka,Ka=null,g()))}function b(g){a(g.instance)}function c(g){return Oa().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(g,function(h){m("failed to asynchronously prepare wasm: "+h);y(h)})}var d={a:xd};E++;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(e.instantiateWasm)try{var f=e.instantiateWasm(d,a);return f=ud(f)}catch(g){return m("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return v||"function"!==typeof WebAssembly.instantiateStreaming||La()||F.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,
d).then(b,function(h){m("wasm streaming compile failed: "+h);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.v).apply(null,arguments)};e._main=function(){return(e._main=e.asm.w).apply(null,arguments)};var xa=e._malloc=function(){return(xa=e._malloc=e.asm.y).apply(null,arguments)},X=e._free=function(){return(X=e._free=e.asm.z).apply(null,arguments)};
e.stackAlloc=function(){return(e.stackAlloc=e.asm.A).apply(null,arguments)};e._asyncify_start_unwind=function(){return(e._asyncify_start_unwind=e.asm.B).apply(null,arguments)};e._asyncify_stop_unwind=function(){return(e._asyncify_stop_unwind=e.asm.C).apply(null,arguments)};e._asyncify_start_rewind=function(){return(e._asyncify_start_rewind=e.asm.D).apply(null,arguments)};e._asyncify_stop_rewind=function(){return(e._asyncify_stop_rewind=e.asm.E).apply(null,arguments)};var yd;
function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ka=function zd(){yd||Ad();yd||(Ka=zd)};
function Ad(){function a(){if(!yd&&(yd=!0,e.calledRun=!0,!B)){e.noFSInit||Lc||(Lc=!0,Kc(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Pc("stdin",e.stdin):Gc("/dev/tty","/dev/stdin"),e.stdout?Pc("stdout",null,e.stdout):Gc("/dev/tty","/dev/stdout"),e.stderr?Pc("stderr",null,e.stderr):Gc("/dev/tty1","/dev/stderr"),Ic("/dev/stdin",0),Ic("/dev/stdout",1),Ic("/dev/stderr",1));sc=!1;Pa(Ea);Pa(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Bd){var b=e._main;try{var c=b(0,0);sb(c)}catch(d){Qa(d)}finally{}}if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ga.unshift(b);Pa(Ga)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ia();Pa(Da);0<E||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=Ad;function sb(a){va=a;noExitRuntime||0<la||(Ha=!0);va=a;if(!(noExitRuntime||0<la)){if(e.onExit)e.onExit(a);B=!0}ba(a,new ka(a))}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Bd=!0;e.noInitialRun&&(Bd=!1);Ad();
